name = "edilrepairstechnology"
main = "index.js"
compatibility_date = "2024-01-30"

[vars]
# scegli UNO dei due modi:
# 1) Diretto:
WHEP_URL = "https://screenstream.io/whep/72500366"

# 2) Oppure componi:
# WHEP_BASE = "https://screenstream.io/whep"
# STREAM_ID = "72500366"

# In entrambi i casi serve la password:
STREAM_PASS = "VDPfNM"
