name = "edilrepairstechnology"
main = "src/worker.js"
compatibility_date = "2024-06-20"

[vars]
# se hai già WHEP_URL completo NON serve WHEP_BASE
WHEP_BASE = "https://screenstream.io/whep"
WHEP_URL  = "https://screenstream.io/whep/72500366"

# usa le tue credenziali di visione dello stream
STREAM_ID = "72500366"
# STREAM_PASS: mettila come secret

# cors aperto (già nel worker)
